apiVersion : apps/v1
kind: Deployment
metadata:
  name: sampleappkai
spec:
  replicas: #replicaNo#
  selector:
    matchLabels:
      app: sampleappkai
  template:
    metadata:
      labels:
        app: sampleappkai 
    spec:
      containers:
        - name: sampleappkai
          image: k8sexamplesacr.azurecr.io/sampleappkai
          ports:
          - containerPort: 80